apiVersion: compute.crossplane.io/v1alpha1
kind: KubernetesCluster
metadata:
  name: rbitrage-dataplane-cluster
  labels:
    app: dataplane-west
spec:
  classSelector:
    matchLabels:
      region: west
  writeConnectionSecretToRef:
    name: rbitrage-dataplane-cluster
